# Generated by Django 4.2.25 on 2025-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
